#!/bin/sh

# PROVIDE: minijail
# REQUIRE: jail
# KEYWORD: shutdown

. /etc/rc.subr

name="minijail"
rcvar="${name}_enable"

load_rc_config $name

: ${minijail_enable="NO"}

stop_cmd="${name}_stop"

minijail_stop()
{
	local JAILS_ROOT

	[ -s /usr/local/etc/minijail.conf ] && . /usr/local/etc/minijail.conf
	: ${JAILS_ROOT:='/var/jails'}
	mounted -p "${JAILS_ROOT}" | while read mnt; do # TODO: full path of mounted
		umount "$mnt"
	done
}

run_rc_command "$1"
